// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("role");
                });

            modelBuilder.Entity("WebAPI.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TokenCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.HasKey("Id");

                    b.HasIndex("Login", "EmailAddress")
                        .IsUnique();

                    b.ToTable("user");
                });

            modelBuilder.Entity("WebAPI.Models.ApplicationUserRole", b =>
                {
                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationUserId", "ApplicationRoleId");

                    b.HasIndex("ApplicationRoleId");

                    b.ToTable("user_role");
                });

            modelBuilder.Entity("WebAPI.Models.ChartOfAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountHeaderName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("AccountHeaderNo")
                        .HasColumnType("int");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("AccountNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountNo")
                        .IsUnique();

                    b.HasIndex("CurrencyId");

                    b.ToTable("chart_of_account");

                    b.HasData(
                        new
                        {
                            Id = new Guid("913e2edf-4e3b-49fc-884c-41876f4bcdb3"),
                            AccountHeaderName = "Asset",
                            AccountHeaderNo = 100,
                            AccountName = "Kas",
                            AccountNo = 111
                        },
                        new
                        {
                            Id = new Guid("87105a71-142b-4c4f-8568-b5ff60aee6eb"),
                            AccountHeaderName = "Asset",
                            AccountHeaderNo = 100,
                            AccountName = "Bank",
                            AccountNo = 112
                        },
                        new
                        {
                            Id = new Guid("7993c1f9-0fcc-4ccf-b19c-2b4add5782bf"),
                            AccountHeaderName = "Asset",
                            AccountHeaderNo = 100,
                            AccountName = "Persediaan",
                            AccountNo = 113
                        },
                        new
                        {
                            Id = new Guid("1fc549e7-c60f-4440-beeb-eb4d6d580992"),
                            AccountHeaderName = "Asset",
                            AccountHeaderNo = 100,
                            AccountName = "Perlengkapan",
                            AccountNo = 114
                        },
                        new
                        {
                            Id = new Guid("573b0f53-ae55-4540-b22f-895f76605db7"),
                            AccountHeaderName = "Asset",
                            AccountHeaderNo = 100,
                            AccountName = "Sewa dibayar di muka",
                            AccountNo = 115
                        },
                        new
                        {
                            Id = new Guid("7fc23dc9-8ddc-4536-978b-6b4a833a8650"),
                            AccountHeaderName = "Asset",
                            AccountHeaderNo = 100,
                            AccountName = "Piutang Dagang",
                            AccountNo = 116
                        },
                        new
                        {
                            Id = new Guid("7a09d43a-8464-4652-bafb-daf8ed0a001c"),
                            AccountHeaderName = "Asset",
                            AccountHeaderNo = 100,
                            AccountName = "Peralatan",
                            AccountNo = 121
                        },
                        new
                        {
                            Id = new Guid("2585e6db-9f52-41f9-b022-6bac4ee39c4e"),
                            AccountHeaderName = "Asset",
                            AccountHeaderNo = 100,
                            AccountName = "Akumulasi Depresiasi - Mesin Cuci",
                            AccountNo = 122
                        },
                        new
                        {
                            Id = new Guid("5014fce0-361a-4b9f-ad3e-2f680ede0030"),
                            AccountHeaderName = "Liabilitas",
                            AccountHeaderNo = 200,
                            AccountName = "Utang Dagang",
                            AccountNo = 201
                        },
                        new
                        {
                            Id = new Guid("0faf503b-3842-4b38-b2ab-82a09a686810"),
                            AccountHeaderName = "Ekuitas",
                            AccountHeaderNo = 300,
                            AccountName = "Ekuitas Pemilik Usaha",
                            AccountNo = 301
                        },
                        new
                        {
                            Id = new Guid("8af02038-2ada-4c2e-899c-353e211049f5"),
                            AccountHeaderName = "Ekuitas",
                            AccountHeaderNo = 300,
                            AccountName = "Laba Ditahan",
                            AccountNo = 310
                        },
                        new
                        {
                            Id = new Guid("11ebb164-b8e0-4757-bd08-7cc409e8faf5"),
                            AccountHeaderName = "Ekuitas",
                            AccountHeaderNo = 300,
                            AccountName = "Ikhtisar Laba-Rugi",
                            AccountNo = 320
                        },
                        new
                        {
                            Id = new Guid("547b9264-083c-406e-b0e7-618f0241568b"),
                            AccountHeaderName = "Pendapatan",
                            AccountHeaderNo = 400,
                            AccountName = "Pendapatan Penjualan",
                            AccountNo = 401
                        },
                        new
                        {
                            Id = new Guid("ddc0e86d-bbb3-49dd-a982-c666f1d16575"),
                            AccountHeaderName = "Pendapatan",
                            AccountHeaderNo = 400,
                            AccountName = "Potongan Penjualan",
                            AccountNo = 420
                        },
                        new
                        {
                            Id = new Guid("77068633-1c07-46d0-b2e8-e919780693ea"),
                            AccountHeaderName = "Harga Pokok Penjualan",
                            AccountHeaderNo = 500,
                            AccountName = "Pembelian",
                            AccountNo = 501
                        },
                        new
                        {
                            Id = new Guid("2cc907e5-9f6b-4dee-a3ab-3b7699fe9dfe"),
                            AccountHeaderName = "Harga Pokok Penjualan",
                            AccountHeaderNo = 500,
                            AccountName = "Potongan Pembelian",
                            AccountNo = 502
                        },
                        new
                        {
                            Id = new Guid("be3fa0e8-7f38-4a9d-82af-1da0a64d4c70"),
                            AccountHeaderName = "Harga Pokok Penjualan",
                            AccountHeaderNo = 500,
                            AccountName = "Persediaan Awal",
                            AccountNo = 511
                        },
                        new
                        {
                            Id = new Guid("b1310f15-6de2-4119-9553-3080d4a660fb"),
                            AccountHeaderName = "Harga Pokok Penjualan",
                            AccountHeaderNo = 500,
                            AccountName = "Persediaan Akhir",
                            AccountNo = 521
                        },
                        new
                        {
                            Id = new Guid("15c09e8c-3439-4ca6-b63e-d0d3c2c2ddeb"),
                            AccountHeaderName = "Pengeluaran",
                            AccountHeaderNo = 600,
                            AccountName = "Beban Gaji",
                            AccountNo = 601
                        },
                        new
                        {
                            Id = new Guid("40ffeb73-be96-4599-8f65-d2ebc9a26c0a"),
                            AccountHeaderName = "Pengeluaran",
                            AccountHeaderNo = 600,
                            AccountName = "Beban Sewa",
                            AccountNo = 602
                        },
                        new
                        {
                            Id = new Guid("d8558de6-29a8-49cc-aea2-da282660cb43"),
                            AccountHeaderName = "Pengeluaran",
                            AccountHeaderNo = 600,
                            AccountName = "Beban Utilitas",
                            AccountNo = 603
                        },
                        new
                        {
                            Id = new Guid("f0a715d4-86ac-4db4-bd44-3561f8e5daaa"),
                            AccountHeaderName = "Pengeluaran",
                            AccountHeaderNo = 600,
                            AccountName = "Beban Listrik",
                            AccountNo = 604
                        },
                        new
                        {
                            Id = new Guid("ebaa3442-0334-4581-9049-1cc80a600c59"),
                            AccountHeaderName = "Pengeluaran",
                            AccountHeaderNo = 600,
                            AccountName = "Beban Perlengkapan",
                            AccountNo = 605
                        },
                        new
                        {
                            Id = new Guid("ed97eb75-10a0-4df6-8e6c-5c11d37ae2cb"),
                            AccountHeaderName = "Pengeluaran",
                            AccountHeaderNo = 600,
                            AccountName = "Beban Depresiasi",
                            AccountNo = 606
                        });
                });

            modelBuilder.Entity("WebAPI.Models.ClosingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("closing_entry");
                });

            modelBuilder.Entity("WebAPI.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("company");

                    b.HasData(
                        new
                        {
                            Id = new Guid("040731b6-c2ce-4842-b134-9a51746f2ca9"),
                            Address = "Ruko Puri Loka Blok E No. 5, Sei Panas, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29411",
                            MobileNumber = "+6282283025500",
                            Name = "BLUE WASH"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CultureName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Code", "CultureName")
                        .IsUnique();

                    b.ToTable("currency");

                    b.HasData(
                        new
                        {
                            Id = new Guid("effcd6d9-4e3a-441f-8f85-fede6cc03967"),
                            Code = "IDR",
                            CultureName = "id-ID",
                            Name = "Indonesia Rupiah"
                        },
                        new
                        {
                            Id = new Guid("a03ef135-1a46-42d8-a0bf-427cf2e0b463"),
                            Code = "SGD",
                            CultureName = "en-SG",
                            Name = "Dollar Singapore"
                        },
                        new
                        {
                            Id = new Guid("16888cd6-6cac-4d2d-b8a4-f26d953cffe9"),
                            Code = "MYR",
                            CultureName = "ms-MY",
                            Name = "Ringgit Malaysia"
                        },
                        new
                        {
                            Id = new Guid("ebbbe2c7-2089-46dd-904d-2ed01a0fc550"),
                            Code = "USD",
                            CultureName = "en-US",
                            Name = "Dollar USD"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerAddress")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("CustomerCode")
                        .IsUnique();

                    b.ToTable("customer");
                });

            modelBuilder.Entity("WebAPI.Models.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ItemNo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemNo")
                        .IsUnique();

                    b.ToTable("inventory");
                });

            modelBuilder.Entity("WebAPI.Models.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClosingEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<string>("TransactionNo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("ClosingEntryId");

                    b.ToTable("journal_entry");
                });

            modelBuilder.Entity("WebAPI.Models.JournalItem", b =>
                {
                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("JournalItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<Guid>("ChartOfAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Credit")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("Debit")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JournalEntryId", "JournalItemId");

                    b.HasIndex("ChartOfAccountId");

                    b.ToTable("journal_item");
                });

            modelBuilder.Entity("WebAPI.Models.LaundryService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LaundryProcess")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("laundry_service");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6e3d879e-9804-47db-8550-fee599a81b5b"),
                            LaundryProcess = 7,
                            Name = "PAKET BULANAN LENGKAP"
                        },
                        new
                        {
                            Id = new Guid("6f02fd67-f4c3-4d73-8856-a3b3c68d9276"),
                            LaundryProcess = 4,
                            Name = "PAKET BULANAN SETRIKA"
                        },
                        new
                        {
                            Id = new Guid("69224789-77cf-44ac-b906-1d7c09868107"),
                            LaundryProcess = 3,
                            Name = "SATUAN"
                        },
                        new
                        {
                            Id = new Guid("85c8f51f-9c9b-4cb7-85ea-742c6f3d22e7"),
                            LaundryProcess = 3,
                            Name = "SEPATU DAN TAS"
                        },
                        new
                        {
                            Id = new Guid("521e5061-495f-4952-96c5-49fc24d27067"),
                            LaundryProcess = 3,
                            Name = "KARPET/GORDEN"
                        },
                        new
                        {
                            Id = new Guid("d925808e-80db-4d69-9059-d2a4720cc0c8"),
                            LaundryProcess = 7,
                            Name = "KILOAN LENGKAP"
                        },
                        new
                        {
                            Id = new Guid("de1ce154-4c00-4f12-a593-a73634b10d67"),
                            LaundryProcess = 7,
                            Name = "KILOAN SETRIKA/CUCI LIPAT"
                        },
                        new
                        {
                            Id = new Guid("23249048-50e4-446d-ae97-bb9993a3c09a"),
                            LaundryProcess = 3,
                            Name = "BED COVER & SELIMUT"
                        },
                        new
                        {
                            Id = new Guid("5e621eab-6b0b-49eb-b018-1425a0da8b72"),
                            LaundryProcess = 3,
                            Name = "SPREI & ALAS KASUR"
                        },
                        new
                        {
                            Id = new Guid("ce192b81-4fcb-4d98-b570-3c556585589a"),
                            LaundryProcess = 3,
                            Name = "BANTAL/BONEKA"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MenuCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MenuDisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MenuSequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuCategoryId", "MenuName")
                        .IsUnique();

                    b.ToTable("menu");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7975f8b8-9f7a-4866-bf06-608daf33a4af"),
                            MenuCategoryId = new Guid("248f896d-1eed-49e4-b7bd-a0a0a37ffb1c"),
                            MenuDisplayName = "Dashboard",
                            MenuName = "dashboard",
                            MenuSequence = 10
                        },
                        new
                        {
                            Id = new Guid("3b616efc-ea0c-4fb8-848a-f1deec14e8c3"),
                            MenuCategoryId = new Guid("7aa59789-75a6-4414-9daf-b64c2fb3ebcd"),
                            MenuDisplayName = "Chart of Account",
                            MenuName = "chart-of-account",
                            MenuSequence = 10
                        },
                        new
                        {
                            Id = new Guid("6c8f0943-2aa5-48fe-beb3-34b6f9928c99"),
                            MenuCategoryId = new Guid("7aa59789-75a6-4414-9daf-b64c2fb3ebcd"),
                            MenuDisplayName = "Pelanggan",
                            MenuName = "customer",
                            MenuSequence = 20
                        },
                        new
                        {
                            Id = new Guid("e429e924-4275-4eff-8926-ce88c3b1dcd3"),
                            MenuCategoryId = new Guid("7aa59789-75a6-4414-9daf-b64c2fb3ebcd"),
                            MenuDisplayName = "Pemasok",
                            MenuName = "supplier",
                            MenuSequence = 30
                        },
                        new
                        {
                            Id = new Guid("3c96056a-8e67-49d7-9496-e5c97ee1e09d"),
                            MenuCategoryId = new Guid("7aa59789-75a6-4414-9daf-b64c2fb3ebcd"),
                            MenuDisplayName = "Persediaan",
                            MenuName = "inventory",
                            MenuSequence = 40
                        },
                        new
                        {
                            Id = new Guid("61a61cb6-6589-4efc-b2be-9a41f067cc32"),
                            MenuCategoryId = new Guid("7aa59789-75a6-4414-9daf-b64c2fb3ebcd"),
                            MenuDisplayName = "Tipe Laundry",
                            MenuName = "laundry-service",
                            MenuSequence = 50
                        },
                        new
                        {
                            Id = new Guid("c200839f-7af3-45c8-91bb-8b0ab7ed66a9"),
                            MenuCategoryId = new Guid("7aa59789-75a6-4414-9daf-b64c2fb3ebcd"),
                            MenuDisplayName = "Menu Harga",
                            MenuName = "price-menu",
                            MenuSequence = 60
                        },
                        new
                        {
                            Id = new Guid("32581d67-ddf0-4a97-aabe-ea486bca3e97"),
                            MenuCategoryId = new Guid("62cee0bc-e597-4f11-bb64-b9b1aa85f0a8"),
                            MenuDisplayName = "Journal Entries",
                            MenuName = "journal-entry",
                            MenuSequence = 10
                        },
                        new
                        {
                            Id = new Guid("f3bc99da-2dfb-46d9-812c-57c301058d2c"),
                            MenuCategoryId = new Guid("62cee0bc-e597-4f11-bb64-b9b1aa85f0a8"),
                            MenuDisplayName = "Closing Entries",
                            MenuName = "closing-entry",
                            MenuSequence = 10
                        },
                        new
                        {
                            Id = new Guid("2fb96518-bfb9-4d54-89a4-45a50698c905"),
                            MenuCategoryId = new Guid("d694f409-4f9c-4692-a42f-2094e3b09008"),
                            MenuDisplayName = "Pembelian",
                            MenuName = "purchase",
                            MenuSequence = 10
                        },
                        new
                        {
                            Id = new Guid("19c7a7d5-811e-4b2a-97e1-e39e791deb78"),
                            MenuCategoryId = new Guid("d694f409-4f9c-4692-a42f-2094e3b09008"),
                            MenuDisplayName = "Pembayaran Pembelian",
                            MenuName = "purchase-payment",
                            MenuSequence = 20
                        },
                        new
                        {
                            Id = new Guid("37c9a181-582c-4dde-9217-98d4dffc7700"),
                            MenuCategoryId = new Guid("3b37be0b-107b-474e-84db-7d66b4982799"),
                            MenuDisplayName = "Penjualan",
                            MenuName = "sales",
                            MenuSequence = 10
                        },
                        new
                        {
                            Id = new Guid("38804e0c-3e19-4044-8229-bb2026970a4d"),
                            MenuCategoryId = new Guid("3b37be0b-107b-474e-84db-7d66b4982799"),
                            MenuDisplayName = "Pembayaran Penjualan",
                            MenuName = "sales-payment",
                            MenuSequence = 20
                        },
                        new
                        {
                            Id = new Guid("73d0eb70-ccf3-4ae8-9c1c-c157839c8bbe"),
                            MenuCategoryId = new Guid("c81512f7-e526-474d-8b52-04e2c7b8f75b"),
                            MenuDisplayName = "Buku Besar",
                            MenuName = "general-ledger",
                            MenuSequence = 10
                        },
                        new
                        {
                            Id = new Guid("2eb6b50f-f53d-4924-a49d-1effae422e64"),
                            MenuCategoryId = new Guid("c81512f7-e526-474d-8b52-04e2c7b8f75b"),
                            MenuDisplayName = "Neraca Saldo",
                            MenuName = "trial-balance",
                            MenuSequence = 20
                        },
                        new
                        {
                            Id = new Guid("a282abe9-3b20-4bb1-b6d9-444d4c1294b4"),
                            MenuCategoryId = new Guid("c81512f7-e526-474d-8b52-04e2c7b8f75b"),
                            MenuDisplayName = "Laba Rugi",
                            MenuName = "income-statement",
                            MenuSequence = 30
                        },
                        new
                        {
                            Id = new Guid("42c2d2cd-3f56-4bc0-840e-8769856edc0f"),
                            MenuCategoryId = new Guid("c81512f7-e526-474d-8b52-04e2c7b8f75b"),
                            MenuDisplayName = "Posisi Keuangan",
                            MenuName = "balance-sheet",
                            MenuSequence = 40
                        },
                        new
                        {
                            Id = new Guid("51ef7e8c-4913-4ebe-a6d0-5dd72ec24c19"),
                            MenuCategoryId = new Guid("c81512f7-e526-474d-8b52-04e2c7b8f75b"),
                            MenuDisplayName = "Pembelian",
                            MenuName = "report-purchase",
                            MenuSequence = 50
                        },
                        new
                        {
                            Id = new Guid("1878d7e6-fce4-4074-8796-3d814f4cd444"),
                            MenuCategoryId = new Guid("c81512f7-e526-474d-8b52-04e2c7b8f75b"),
                            MenuDisplayName = "Penjualan",
                            MenuName = "report-sales",
                            MenuSequence = 60
                        },
                        new
                        {
                            Id = new Guid("0906c674-b075-4f2d-b54f-43236c9d03ea"),
                            MenuCategoryId = new Guid("b71ed8ec-6644-4f0e-862e-de4a383d36d7"),
                            MenuDisplayName = "Perusahaan",
                            MenuName = "company",
                            MenuSequence = 10
                        },
                        new
                        {
                            Id = new Guid("598b71b8-338e-4fa2-95ed-b3f97cfcd252"),
                            MenuCategoryId = new Guid("b71ed8ec-6644-4f0e-862e-de4a383d36d7"),
                            MenuDisplayName = "Template WhatsApp",
                            MenuName = "message-template",
                            MenuSequence = 100
                        });
                });

            modelBuilder.Entity("WebAPI.Models.MenuCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryDisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategorySequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("menu_category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("248f896d-1eed-49e4-b7bd-a0a0a37ffb1c"),
                            CategoryDisplayName = "Dashboard",
                            CategoryName = "dashboard",
                            CategorySequence = 10
                        },
                        new
                        {
                            Id = new Guid("7aa59789-75a6-4414-9daf-b64c2fb3ebcd"),
                            CategoryDisplayName = "Master Data",
                            CategoryName = "master-data",
                            CategorySequence = 20
                        },
                        new
                        {
                            Id = new Guid("62cee0bc-e597-4f11-bb64-b9b1aa85f0a8"),
                            CategoryDisplayName = "Accounting",
                            CategoryName = "accounting",
                            CategorySequence = 30
                        },
                        new
                        {
                            Id = new Guid("d694f409-4f9c-4692-a42f-2094e3b09008"),
                            CategoryDisplayName = "Purchase",
                            CategoryName = "purchase",
                            CategorySequence = 40
                        },
                        new
                        {
                            Id = new Guid("3b37be0b-107b-474e-84db-7d66b4982799"),
                            CategoryDisplayName = "Sales",
                            CategoryName = "sales",
                            CategorySequence = 50
                        },
                        new
                        {
                            Id = new Guid("c81512f7-e526-474d-8b52-04e2c7b8f75b"),
                            CategoryDisplayName = "Report",
                            CategoryName = "report",
                            CategorySequence = 60
                        },
                        new
                        {
                            Id = new Guid("b71ed8ec-6644-4f0e-862e-de4a383d36d7"),
                            CategoryDisplayName = "Configuration",
                            CategoryName = "configuration",
                            CategorySequence = 1000
                        });
                });

            modelBuilder.Entity("WebAPI.Models.MessageTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Template")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("message_template");
                });

            modelBuilder.Entity("WebAPI.Models.PriceMenu", b =>
                {
                    b.Property<Guid>("LaundryServiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("PriceMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(19, 3)
                        .HasColumnType("decimal(19,3)");

                    b.Property<string>("PricingOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessingTime")
                        .HasColumnType("int");

                    b.Property<string>("TimeUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LaundryServiceId", "PriceMenuId");

                    b.HasIndex("LaundryServiceId", "Name", "DeliveryOption")
                        .IsUnique();

                    b.ToTable("price_menu");

                    b.HasData(
                        new
                        {
                            LaundryServiceId = new Guid("6e3d879e-9804-47db-8550-fee599a81b5b"),
                            PriceMenuId = new Guid("222744c7-845a-4c8b-b023-1cd488965784"),
                            DeliveryOption = "None",
                            Name = "25 Kgs",
                            Price = 140000m,
                            PricingOption = "Package",
                            ProcessingTime = 0,
                            TimeUnit = "None"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("6e3d879e-9804-47db-8550-fee599a81b5b"),
                            PriceMenuId = new Guid("afbc2e8a-e324-4baf-994e-2703221d0f49"),
                            DeliveryOption = "None",
                            Name = "50 Kgs",
                            Price = 275000m,
                            PricingOption = "Package",
                            ProcessingTime = 0,
                            TimeUnit = "None"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("6e3d879e-9804-47db-8550-fee599a81b5b"),
                            PriceMenuId = new Guid("02f2aad2-e154-4454-9ea2-f71dc88b7896"),
                            DeliveryOption = "None",
                            Name = "100 Kgs",
                            Price = 550000m,
                            PricingOption = "Package",
                            ProcessingTime = 0,
                            TimeUnit = "None"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("6f02fd67-f4c3-4d73-8856-a3b3c68d9276"),
                            PriceMenuId = new Guid("39d2e31c-fca5-4f44-8bf7-d0bec5027d79"),
                            DeliveryOption = "None",
                            Name = "25 Kgs",
                            Price = 120000m,
                            PricingOption = "Package",
                            ProcessingTime = 0,
                            TimeUnit = "None"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("6f02fd67-f4c3-4d73-8856-a3b3c68d9276"),
                            PriceMenuId = new Guid("bd4cb094-193e-4712-bed6-02ef2d91b30f"),
                            DeliveryOption = "None",
                            Name = "50 Kgs",
                            Price = 240000m,
                            PricingOption = "Package",
                            ProcessingTime = 0,
                            TimeUnit = "None"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("6f02fd67-f4c3-4d73-8856-a3b3c68d9276"),
                            PriceMenuId = new Guid("3330723b-eb73-439d-8bcd-4e7a11dfe760"),
                            DeliveryOption = "None",
                            Name = "100 Kgs",
                            Price = 475000m,
                            PricingOption = "Package",
                            ProcessingTime = 0,
                            TimeUnit = "None"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("69224789-77cf-44ac-b906-1d7c09868107"),
                            PriceMenuId = new Guid("10fc601c-c2e1-4b3d-9c59-6038981391b2"),
                            DeliveryOption = "Reguler",
                            Name = "Bawahan",
                            Price = 10000m,
                            PricingOption = "Unit",
                            ProcessingTime = 2,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("69224789-77cf-44ac-b906-1d7c09868107"),
                            PriceMenuId = new Guid("00da1441-6fd1-46af-9d68-ae49cb00bc7f"),
                            DeliveryOption = "Reguler",
                            Name = "Atasan",
                            Price = 10000m,
                            PricingOption = "Unit",
                            ProcessingTime = 2,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("69224789-77cf-44ac-b906-1d7c09868107"),
                            PriceMenuId = new Guid("e8663646-4523-42bc-9916-14c7788eb9dd"),
                            DeliveryOption = "Reguler",
                            Name = "Jas",
                            Price = 20000m,
                            PricingOption = "Unit",
                            ProcessingTime = 2,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("69224789-77cf-44ac-b906-1d7c09868107"),
                            PriceMenuId = new Guid("ca3da966-ed51-42bc-8c37-698a8ca24b26"),
                            DeliveryOption = "Reguler",
                            Name = "Jas Set",
                            Price = 30000m,
                            PricingOption = "Unit",
                            ProcessingTime = 2,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("69224789-77cf-44ac-b906-1d7c09868107"),
                            PriceMenuId = new Guid("a4c5c479-7364-406e-8acd-a761161293eb"),
                            DeliveryOption = "Reguler",
                            Name = "Blazer",
                            Price = 15000m,
                            PricingOption = "Unit",
                            ProcessingTime = 2,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("69224789-77cf-44ac-b906-1d7c09868107"),
                            PriceMenuId = new Guid("81305acb-43e8-4245-b7e7-ac79b25a5e20"),
                            DeliveryOption = "Reguler",
                            Name = "Blazer Set",
                            Price = 25000m,
                            PricingOption = "Unit",
                            ProcessingTime = 2,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("69224789-77cf-44ac-b906-1d7c09868107"),
                            PriceMenuId = new Guid("65f2160e-5977-4488-bc8c-98de3e3655f4"),
                            DeliveryOption = "Reguler",
                            Name = "Dress Panjang",
                            Price = 15000m,
                            PricingOption = "Unit",
                            ProcessingTime = 2,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("69224789-77cf-44ac-b906-1d7c09868107"),
                            PriceMenuId = new Guid("1f70dd2e-b01d-4fb5-b573-4c86a18ec326"),
                            DeliveryOption = "Reguler",
                            Name = "Dress Pendek",
                            Price = 15000m,
                            PricingOption = "Unit",
                            ProcessingTime = 2,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("69224789-77cf-44ac-b906-1d7c09868107"),
                            PriceMenuId = new Guid("994ef033-b02d-4452-83b6-e24c22294d91"),
                            DeliveryOption = "Reguler",
                            Name = "Jaket/Sweater",
                            Price = 15000m,
                            PricingOption = "Unit",
                            ProcessingTime = 2,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("69224789-77cf-44ac-b906-1d7c09868107"),
                            PriceMenuId = new Guid("036a5843-d09a-4c6c-bd92-f7036e706857"),
                            DeliveryOption = "Reguler",
                            Name = "Handuk Besar",
                            Price = 7000m,
                            PricingOption = "Unit",
                            ProcessingTime = 2,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("69224789-77cf-44ac-b906-1d7c09868107"),
                            PriceMenuId = new Guid("b1a8839a-9bde-450f-8eea-fbc7e1c0fc4d"),
                            DeliveryOption = "Reguler",
                            Name = "Handuk Sedang",
                            Price = 6000m,
                            PricingOption = "Unit",
                            ProcessingTime = 2,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("85c8f51f-9c9b-4cb7-85ea-742c6f3d22e7"),
                            PriceMenuId = new Guid("abd24f3c-8784-4329-af85-af5431cf830f"),
                            DeliveryOption = "Reguler",
                            Name = "Sepatu",
                            Price = 25000m,
                            PricingOption = "Unit",
                            ProcessingTime = 2,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("85c8f51f-9c9b-4cb7-85ea-742c6f3d22e7"),
                            PriceMenuId = new Guid("238f014a-e593-4d13-946b-8aebda6d6f86"),
                            DeliveryOption = "Reguler",
                            Name = "Tas Besar",
                            Price = 30000m,
                            PricingOption = "Unit",
                            ProcessingTime = 2,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("85c8f51f-9c9b-4cb7-85ea-742c6f3d22e7"),
                            PriceMenuId = new Guid("1a5a3143-a7a4-4335-be68-d4195601977f"),
                            DeliveryOption = "Reguler",
                            Name = "Tas Sedang",
                            Price = 25000m,
                            PricingOption = "Unit",
                            ProcessingTime = 2,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("85c8f51f-9c9b-4cb7-85ea-742c6f3d22e7"),
                            PriceMenuId = new Guid("1cc74945-64ee-4933-8147-1a01760e9c8a"),
                            DeliveryOption = "Reguler",
                            Name = "Tas Kecil",
                            Price = 15000m,
                            PricingOption = "Unit",
                            ProcessingTime = 2,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("85c8f51f-9c9b-4cb7-85ea-742c6f3d22e7"),
                            PriceMenuId = new Guid("3e7ecae5-adf9-40f8-9d00-a11f25c30eee"),
                            DeliveryOption = "Reguler",
                            Name = "Tas Mini",
                            Price = 10000m,
                            PricingOption = "Unit",
                            ProcessingTime = 2,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("d925808e-80db-4d69-9059-d2a4720cc0c8"),
                            PriceMenuId = new Guid("a7dfabc2-89e7-4d4e-b7db-9afadeb7ab39"),
                            DeliveryOption = "Reguler",
                            Name = "Reguler",
                            Price = 6000m,
                            PricingOption = "Kilogram",
                            ProcessingTime = 2,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("d925808e-80db-4d69-9059-d2a4720cc0c8"),
                            PriceMenuId = new Guid("2afa7cd8-c18b-4aab-b9be-3767a9ff2a2c"),
                            DeliveryOption = "OneDay",
                            Name = "One Day",
                            Price = 8000m,
                            PricingOption = "Kilogram",
                            ProcessingTime = 1,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("d925808e-80db-4d69-9059-d2a4720cc0c8"),
                            PriceMenuId = new Guid("90cb34d3-a294-47a1-b39a-c21b3a740547"),
                            DeliveryOption = "Express",
                            Name = "Express",
                            Price = 10000m,
                            PricingOption = "Kilogram",
                            ProcessingTime = 6,
                            TimeUnit = "Hour"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("de1ce154-4c00-4f12-a593-a73634b10d67"),
                            PriceMenuId = new Guid("a73c9ccf-1cd6-4b3b-adc5-b273112a7811"),
                            DeliveryOption = "Reguler",
                            Name = "Reguler",
                            Price = 5000m,
                            PricingOption = "Kilogram",
                            ProcessingTime = 2,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("de1ce154-4c00-4f12-a593-a73634b10d67"),
                            PriceMenuId = new Guid("5c86719c-f26f-423a-bd22-de328af45222"),
                            DeliveryOption = "OneDay",
                            Name = "One Day",
                            Price = 7000m,
                            PricingOption = "Kilogram",
                            ProcessingTime = 1,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("de1ce154-4c00-4f12-a593-a73634b10d67"),
                            PriceMenuId = new Guid("90539d35-6fe7-460d-85bf-911c93588903"),
                            DeliveryOption = "Express",
                            Name = "Express",
                            Price = 9000m,
                            PricingOption = "Kilogram",
                            ProcessingTime = 6,
                            TimeUnit = "Hour"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("23249048-50e4-446d-ae97-bb9993a3c09a"),
                            PriceMenuId = new Guid("433ffecc-398f-43b7-9bb4-b48e77d15b76"),
                            DeliveryOption = "Reguler",
                            Name = "Bed Cover King Set",
                            Price = 38000m,
                            PricingOption = "Set",
                            ProcessingTime = 3,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("23249048-50e4-446d-ae97-bb9993a3c09a"),
                            PriceMenuId = new Guid("e1ebbf40-6911-4178-b68a-1d24f7cb76ee"),
                            DeliveryOption = "Reguler",
                            Name = "Bed Cover Queen Set",
                            Price = 35000m,
                            PricingOption = "Set",
                            ProcessingTime = 3,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("23249048-50e4-446d-ae97-bb9993a3c09a"),
                            PriceMenuId = new Guid("493d5a0f-6fa2-4815-a41c-3122274ccb97"),
                            DeliveryOption = "Reguler",
                            Name = "Bed Cover Single Set",
                            Price = 27000m,
                            PricingOption = "Set",
                            ProcessingTime = 3,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("23249048-50e4-446d-ae97-bb9993a3c09a"),
                            PriceMenuId = new Guid("e3766c6c-6237-454b-a59d-f804daf81bc0"),
                            DeliveryOption = "Reguler",
                            Name = "Bed Cover King",
                            Price = 25000m,
                            PricingOption = "Unit",
                            ProcessingTime = 3,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("23249048-50e4-446d-ae97-bb9993a3c09a"),
                            PriceMenuId = new Guid("3c8812fb-7759-4b2a-aa88-82a0b4116519"),
                            DeliveryOption = "Reguler",
                            Name = "Bed Cover Queen",
                            Price = 20000m,
                            PricingOption = "Unit",
                            ProcessingTime = 3,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("23249048-50e4-446d-ae97-bb9993a3c09a"),
                            PriceMenuId = new Guid("f1d1ce2e-5555-481b-8a63-c1fec3b5da4d"),
                            DeliveryOption = "Reguler",
                            Name = "Bed Cover Single",
                            Price = 15000m,
                            PricingOption = "Unit",
                            ProcessingTime = 3,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("23249048-50e4-446d-ae97-bb9993a3c09a"),
                            PriceMenuId = new Guid("20c0b667-f491-4aae-8374-e7ed5928f9c1"),
                            DeliveryOption = "Reguler",
                            Name = "Selimut",
                            Price = 15000m,
                            PricingOption = "Unit",
                            ProcessingTime = 3,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("23249048-50e4-446d-ae97-bb9993a3c09a"),
                            PriceMenuId = new Guid("93e89b35-55fb-4069-b60f-1f55ad37ae60"),
                            DeliveryOption = "Reguler",
                            Name = "Selimut Tipis",
                            Price = 10000m,
                            PricingOption = "Unit",
                            ProcessingTime = 3,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("23249048-50e4-446d-ae97-bb9993a3c09a"),
                            PriceMenuId = new Guid("79346961-e03e-49ce-a356-b5f836fa4555"),
                            DeliveryOption = "Express",
                            Name = "Bed Cover King Set",
                            Price = 76000m,
                            PricingOption = "Set",
                            ProcessingTime = 6,
                            TimeUnit = "Hour"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("23249048-50e4-446d-ae97-bb9993a3c09a"),
                            PriceMenuId = new Guid("1e00fa06-7de4-4b9d-94bc-00310f15a160"),
                            DeliveryOption = "Express",
                            Name = "Bed Cover Queen Set",
                            Price = 70000m,
                            PricingOption = "Set",
                            ProcessingTime = 6,
                            TimeUnit = "Hour"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("23249048-50e4-446d-ae97-bb9993a3c09a"),
                            PriceMenuId = new Guid("0761f843-b8ec-4f55-bf1f-64af6de3b417"),
                            DeliveryOption = "Express",
                            Name = "Bed Cover Single Set",
                            Price = 54000m,
                            PricingOption = "Set",
                            ProcessingTime = 6,
                            TimeUnit = "Hour"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("23249048-50e4-446d-ae97-bb9993a3c09a"),
                            PriceMenuId = new Guid("983a9b58-09f0-4d9f-b453-138ee6aa6cb5"),
                            DeliveryOption = "Express",
                            Name = "Bed Cover King",
                            Price = 50000m,
                            PricingOption = "Unit",
                            ProcessingTime = 6,
                            TimeUnit = "Hour"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("23249048-50e4-446d-ae97-bb9993a3c09a"),
                            PriceMenuId = new Guid("b678f1a9-7aed-402f-b348-88dee8901b8e"),
                            DeliveryOption = "Express",
                            Name = "Bed Cover Queen",
                            Price = 40000m,
                            PricingOption = "Unit",
                            ProcessingTime = 6,
                            TimeUnit = "Hour"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("23249048-50e4-446d-ae97-bb9993a3c09a"),
                            PriceMenuId = new Guid("aee4b233-74e4-41a2-988a-70c52ed50292"),
                            DeliveryOption = "Express",
                            Name = "Bed Cover Single",
                            Price = 30000m,
                            PricingOption = "Unit",
                            ProcessingTime = 6,
                            TimeUnit = "Hour"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("23249048-50e4-446d-ae97-bb9993a3c09a"),
                            PriceMenuId = new Guid("aa50318f-d0a2-4c30-8c0d-dc447807311e"),
                            DeliveryOption = "Express",
                            Name = "Selimut",
                            Price = 30000m,
                            PricingOption = "Unit",
                            ProcessingTime = 6,
                            TimeUnit = "Hour"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("23249048-50e4-446d-ae97-bb9993a3c09a"),
                            PriceMenuId = new Guid("ad7d2d80-2bee-4112-8029-88cdae7b730e"),
                            DeliveryOption = "Express",
                            Name = "Selimut Tipis",
                            Price = 20000m,
                            PricingOption = "Unit",
                            ProcessingTime = 6,
                            TimeUnit = "Hour"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("5e621eab-6b0b-49eb-b018-1425a0da8b72"),
                            PriceMenuId = new Guid("04f6d6d9-874f-4b2b-90cc-72450c767a42"),
                            DeliveryOption = "Reguler",
                            Name = "Sprei King Set",
                            Price = 20000m,
                            PricingOption = "Set",
                            ProcessingTime = 3,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("5e621eab-6b0b-49eb-b018-1425a0da8b72"),
                            PriceMenuId = new Guid("954df4a5-e9c8-4a05-b893-2e8a68da9171"),
                            DeliveryOption = "Reguler",
                            Name = "Sprei Quen Set",
                            Price = 20000m,
                            PricingOption = "Set",
                            ProcessingTime = 3,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("5e621eab-6b0b-49eb-b018-1425a0da8b72"),
                            PriceMenuId = new Guid("8b99aa71-ec4f-4d90-8dd5-8b1a19b92945"),
                            DeliveryOption = "Reguler",
                            Name = "Sprei Single Set",
                            Price = 15000m,
                            PricingOption = "Set",
                            ProcessingTime = 3,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("5e621eab-6b0b-49eb-b018-1425a0da8b72"),
                            PriceMenuId = new Guid("f38cbf47-f2ce-4f39-9bdb-2b769c1614c7"),
                            DeliveryOption = "Reguler",
                            Name = "Sprei King",
                            Price = 15000m,
                            PricingOption = "Unit",
                            ProcessingTime = 3,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("5e621eab-6b0b-49eb-b018-1425a0da8b72"),
                            PriceMenuId = new Guid("f8214070-d518-4965-a864-b0611169b4b7"),
                            DeliveryOption = "Reguler",
                            Name = "Sprei Queen",
                            Price = 15000m,
                            PricingOption = "Unit",
                            ProcessingTime = 3,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("5e621eab-6b0b-49eb-b018-1425a0da8b72"),
                            PriceMenuId = new Guid("915970c9-6e07-4101-8e82-bde2b935b454"),
                            DeliveryOption = "Reguler",
                            Name = "Sprei Single",
                            Price = 10000m,
                            PricingOption = "Unit",
                            ProcessingTime = 3,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("5e621eab-6b0b-49eb-b018-1425a0da8b72"),
                            PriceMenuId = new Guid("90e19c42-a89b-4a29-82bc-04066b19f35c"),
                            DeliveryOption = "Reguler",
                            Name = "Alas Kasur King",
                            Price = 25000m,
                            PricingOption = "Unit",
                            ProcessingTime = 3,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("5e621eab-6b0b-49eb-b018-1425a0da8b72"),
                            PriceMenuId = new Guid("cdf2af80-d63f-4585-8a41-200bcea47660"),
                            DeliveryOption = "Reguler",
                            Name = "Alas Kasur Queen",
                            Price = 20000m,
                            PricingOption = "Unit",
                            ProcessingTime = 3,
                            TimeUnit = "Day"
                        },
                        new
                        {
                            LaundryServiceId = new Guid("5e621eab-6b0b-49eb-b018-1425a0da8b72"),
                            PriceMenuId = new Guid("2a527b55-4947-448c-a56c-1afb523b09c0"),
                            DeliveryOption = "Reguler",
                            Name = "Alas Kasur Single",
                            Price = 15000m,
                            PricingOption = "Unit",
                            ProcessingTime = 3,
                            TimeUnit = "Day"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.PurchaseDetail", b =>
                {
                    b.Property<Guid>("PurchaseHeaderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("PurchaseDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("PurchaseHeaderId", "PurchaseDetailId");

                    b.HasIndex("InventoryId");

                    b.ToTable("purchase_detail");
                });

            modelBuilder.Entity("WebAPI.Models.PurchaseHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("PurchaseNo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("SupplierId");

                    b.ToTable("purchase_header");
                });

            modelBuilder.Entity("WebAPI.Models.PurchasePayment", b =>
                {
                    b.Property<Guid>("PurchasePaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<Guid>("PurchaseHeaderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PurchasePaymentId", "PurchaseHeaderId");

                    b.HasIndex("PurchaseHeaderId");

                    b.ToTable("purchase_payment", t =>
                        {
                            t.HasTrigger("trgUpdatePurchaseHeaderPaymentStatus");
                        });
                });

            modelBuilder.Entity("WebAPI.Models.SalesDetail", b =>
                {
                    b.Property<Guid>("SalesHeaderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("SalesDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LaundryServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("PriceMenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("SalesHeaderId", "SalesDetailId");

                    b.HasIndex("LaundryServiceId", "PriceMenuId");

                    b.ToTable("sales_detail");
                });

            modelBuilder.Entity("WebAPI.Models.SalesHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SalesDate")
                        .HasColumnType("date");

                    b.Property<string>("SalesNo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("sales_header");
                });

            modelBuilder.Entity("WebAPI.Models.SalesPayment", b =>
                {
                    b.Property<Guid>("SalesPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<Guid>("SalesHeaderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SalesPaymentId", "SalesHeaderId");

                    b.HasIndex("SalesHeaderId");

                    b.ToTable("sales_payment", t =>
                        {
                            t.HasTrigger("trgUpdateSalesHeaderPaymentStatus");
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("SupplierCode")
                        .IsUnique();

                    b.ToTable("supplier");
                });

            modelBuilder.Entity("WebAPI.Models.UserMenu", b =>
                {
                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationUserId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("user_menu");
                });

            modelBuilder.Entity("WebAPI.Models.ApplicationUserRole", b =>
                {
                    b.HasOne("WebAPI.Models.ApplicationRole", "ApplicationRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("ApplicationRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationRole");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("WebAPI.Models.ChartOfAccount", b =>
                {
                    b.HasOne("WebAPI.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("WebAPI.Models.Customer", b =>
                {
                    b.HasOne("WebAPI.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("WebAPI.Models.JournalEntry", b =>
                {
                    b.HasOne("WebAPI.Models.ClosingEntry", "ClosingEntry")
                        .WithMany("JournalEntries")
                        .HasForeignKey("ClosingEntryId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("ClosingEntry");
                });

            modelBuilder.Entity("WebAPI.Models.JournalItem", b =>
                {
                    b.HasOne("WebAPI.Models.ChartOfAccount", "ChartOfAccount")
                        .WithMany("JournalItems")
                        .HasForeignKey("ChartOfAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.JournalEntry", "JournalEntry")
                        .WithMany("JournalItems")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChartOfAccount");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("WebAPI.Models.Menu", b =>
                {
                    b.HasOne("WebAPI.Models.MenuCategory", "MenuCategory")
                        .WithMany("Menus")
                        .HasForeignKey("MenuCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuCategory");
                });

            modelBuilder.Entity("WebAPI.Models.PriceMenu", b =>
                {
                    b.HasOne("WebAPI.Models.LaundryService", "LaundryService")
                        .WithMany("PriceMenus")
                        .HasForeignKey("LaundryServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LaundryService");
                });

            modelBuilder.Entity("WebAPI.Models.PurchaseDetail", b =>
                {
                    b.HasOne("WebAPI.Models.Inventory", "Inventory")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.PurchaseHeader", "PurchaseHeader")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("PurchaseHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("PurchaseHeader");
                });

            modelBuilder.Entity("WebAPI.Models.PurchaseHeader", b =>
                {
                    b.HasOne("WebAPI.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.HasOne("WebAPI.Models.Supplier", "Supplier")
                        .WithMany("PurchaseHeaders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WebAPI.Models.PurchasePayment", b =>
                {
                    b.HasOne("WebAPI.Models.PurchaseHeader", "PurchaseHeader")
                        .WithMany("PurchasePayments")
                        .HasForeignKey("PurchaseHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseHeader");
                });

            modelBuilder.Entity("WebAPI.Models.SalesDetail", b =>
                {
                    b.HasOne("WebAPI.Models.LaundryService", "LaundryService")
                        .WithMany()
                        .HasForeignKey("LaundryServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.SalesHeader", "SalesHeader")
                        .WithMany("SalesDetails")
                        .HasForeignKey("SalesHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.PriceMenu", "PriceMenu")
                        .WithMany("SalesDetails")
                        .HasForeignKey("LaundryServiceId", "PriceMenuId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("LaundryService");

                    b.Navigation("PriceMenu");

                    b.Navigation("SalesHeader");
                });

            modelBuilder.Entity("WebAPI.Models.SalesHeader", b =>
                {
                    b.HasOne("WebAPI.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.HasOne("WebAPI.Models.Customer", "Customer")
                        .WithMany("SalesHeaders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WebAPI.Models.SalesPayment", b =>
                {
                    b.HasOne("WebAPI.Models.SalesHeader", "SalesHeader")
                        .WithMany("SalesPayments")
                        .HasForeignKey("SalesHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesHeader");
                });

            modelBuilder.Entity("WebAPI.Models.Supplier", b =>
                {
                    b.HasOne("WebAPI.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("WebAPI.Models.UserMenu", b =>
                {
                    b.HasOne("WebAPI.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("UserMenus")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.Menu", "Menu")
                        .WithMany("UserMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("WebAPI.Models.ApplicationRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("WebAPI.Models.ApplicationUser", b =>
                {
                    b.Navigation("UserMenus");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("WebAPI.Models.ChartOfAccount", b =>
                {
                    b.Navigation("JournalItems");
                });

            modelBuilder.Entity("WebAPI.Models.ClosingEntry", b =>
                {
                    b.Navigation("JournalEntries");
                });

            modelBuilder.Entity("WebAPI.Models.Customer", b =>
                {
                    b.Navigation("SalesHeaders");
                });

            modelBuilder.Entity("WebAPI.Models.Inventory", b =>
                {
                    b.Navigation("PurchaseDetails");
                });

            modelBuilder.Entity("WebAPI.Models.JournalEntry", b =>
                {
                    b.Navigation("JournalItems");
                });

            modelBuilder.Entity("WebAPI.Models.LaundryService", b =>
                {
                    b.Navigation("PriceMenus");
                });

            modelBuilder.Entity("WebAPI.Models.Menu", b =>
                {
                    b.Navigation("UserMenus");
                });

            modelBuilder.Entity("WebAPI.Models.MenuCategory", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("WebAPI.Models.PriceMenu", b =>
                {
                    b.Navigation("SalesDetails");
                });

            modelBuilder.Entity("WebAPI.Models.PurchaseHeader", b =>
                {
                    b.Navigation("PurchaseDetails");

                    b.Navigation("PurchasePayments");
                });

            modelBuilder.Entity("WebAPI.Models.SalesHeader", b =>
                {
                    b.Navigation("SalesDetails");

                    b.Navigation("SalesPayments");
                });

            modelBuilder.Entity("WebAPI.Models.Supplier", b =>
                {
                    b.Navigation("PurchaseHeaders");
                });
#pragma warning restore 612, 618
        }
    }
}
